version: '3'

services:
    grunt:
        container_name: grunt
        image: grunt
        build: .
        volumes:
            - "./src/www:/src/www"
            # - "./src/Gruntfile.js:/src/Gruntfile.js"
            - "/src/node_modules"
        tty: true